config/routes.rb
Rails.application.routes.draw do
  resources :print_barcode_temps, only: [:new, :create] do    
    collection do
      get "search_product"
      get "add_product"
    end
  end
  resources :accounts_receivable_payments, except: [:edit, :update, :destroy] do
    collection do
      get "generate_form"
      get "get_account_numbers"
    end
  end
  resources :accounts_receivable_invoices, only: [:index, :show] do
    collection do
      get "customer_debts"
      get 'overdue_invoice_list'
    end
    member do
      get "print"
    end
  end
  resources :account_payable_courier_payments, except: [:edit, :update, :destroy] do
    collection do
      get "generate_form"
      get "get_account_numbers"
    end
    member do
      get "print"
    end
  end
  resources :account_payable_couriers, except: [:edit, :update] do
    collection do
      get "get_packing_lists"
      get 'overdue_invoice_list'
    end
    member do
      get "print"
    end
  end  
  resources :general_variables, except: [:show, :destroy, :index]
  resources :packing_lists, except: [:edit, :update] do
    member do
      get 'print'
    end
    collection do
      get 'get_courier_ways'
      get 'get_courier_units'
      get 'get_courier_price_types'
      get 'get_courier_cities'
      get 'generate_packing_list_item_form'
      get :autocomplete_shipment_number
    end
  end
  resources :courier_prices do
    collection do
      get "get_courier_ways"
      get "get_courier_units"
    end
  end
  resources :account_payable_payments, except: [:edit, :update, :destroy] do
    collection do
      get "generate_form"
      get 'get_purchase_returns'
      get 'select_purchase_return'
      get "get_account_numbers"
    end
    member do
      get "print"
    end
  end
  resources :adjustments, except: [:edit, :update, :destroy] do
    collection do
      get :autocomplete_product_code
      get :get_product
    end
  end
  get 'import_beginning_stocks' => 'import_beginning_stocks#new'

  post 'import_beginning_stocks/create'

  get 'sell_thru' => 'sell_thrus#index'
  get 'quantity_sold_charts/index'
  resources :targets
  get 'growth_reports/index'
  get 'growth_reports/print'
  get 'growth_reports/export'

  namespace :api, defaults: { format: :json } do
    resources :stock_mutations do
      collection do
        get "store_to_store_inventory_receipts"
        get "search"
      end
      member do
        get "receive"
      end
    end
    resources :consignment_sales do
      collection do
        get "get_events"
        get "get_product"
      end
      member do
        get "approve"
        get "unapprove"
      end
    end
    resources :shipments, except: [:edit, :update] do
      collection do
        get "inventory_receipts"
        get "search_do"
      end
      member do
        get "receive"
      end
    end
    devise_for :users, only: :sessions
  end

  resources :customers do
    collection do
      get "get_cities"
    end
  end
  resources :consignment_sales do
    collection do
      get "get_product"
      get "get_product_colors"
      get "get_product_sizes"
      get "get_events"
    end
    member do
      get "approve"
      get "unapprove"
    end
  end
  get 'incompatible_browsers/index'

  resources :sales_returns, except: [:edit, :update, :destroy] do
    collection do
      get "search_receipt"
      get "get_replacement_product"
      get "get_replacement_product_colors"
      get "get_replacement_product_sizes"
    end
  end
  

  resources :counter_events do
    collection do
      get "generate_warehouse_form"
      get "add_products"
      get "add_general_products"
      get "get_warehouse"
    end
    member do
      get "generate_activation_form"
      patch "activate_deactivate"
    end
  end
  resources :companies
  resources :sales, except: [:edit, :update, :destroy] do
    collection do
      get "get_member"
      get "get_product"
      get "get_free_product"
      get "get_product_colors"
      get "get_free_product_colors"
      get "get_product_sizes"
      get "get_free_product_sizes"
      get "get_gift_event_product"
      get "get_gift_event_product_colors"
      get "get_gift_event_product_sizes"
      get 'export'
      get 'get_stock_detail'
      get 'search_product'
    end
    member do
      get "print"
      get "print_return_receipt"
    end
  end
  resources :members
  resources :banks, except: :show
  resources :cash_disbursements, only: [:index, :new, :create]
  resources :cashier_openings, except: [:edit, :update, :destroy] do
    member do
      get "close"
    end
  end
  resources :events do
    collection do
      get :autocomplete_events
      post :new_add_general_products
      post :new_add_products
      get "generate_warehouse_form"
      get "add_products"
      get "add_general_products"
    end
    member do
      get "generate_activation_form"
      patch "activate_deactivate"
    end
  end
  resources :listing_stocks, only: :index do
    collection do
      get :print
    end
  end
  resources :stock_movements, only: :index do
    collection do
      get :print
    end
  end
  resources :fiscal_years
  resources :goods_in_transits, only: [:shipment_goods, :mutation_goods, :returned_goods] do
    collection do
      get "shipment_goods"
      get "mutation_goods"
      get "returned_goods"
    end
    member do
      get "show_shipment_goods"
      get "show_mutation_goods"
      get "show_returned_goods"
    end
  end

  resources :stock_mutations do
    collection do
      get "get_products"
      get "get_saved_products"
      get "index_store_to_warehouse_mutation"
      get "show_store_to_warehouse_mutation"
      get "new_store_to_warehouse_mutation"
      get "store_to_store_inventory_receipts"
      get "store_to_warehouse_inventory_receipts"
      post "create_store_to_warehouse_mutation"
      get "search"
    end
    member do
      get "approve"
      get "show_store_to_store_receipt"
      get "show_store_to_warehouse_receipt"
      get "receive"
      get "receive_to_warehouse"
      get "print_rolling_doc"
      get "print_return_doc"
      delete "delete_store_to_warehouse"
      get "change_receive_date"
    end
  end
  resources :notifications, only: [:index, :show, :destroy, :notify_user] do
    collection do
      get "notify_user"
    end
  end
  resources :available_menus, only: [:new, :create]
  resources :shipments, except: [:edit, :update] do
    collection do
      get "generate_ob_detail"
      get "inventory_receipts"
      get "search_do"
      get :multiprint
      get :direct_sales
    end
    member do
      get "receive"
      get "change_receive_date"
      get "print"
      get "show_direct_sale"
    end
  end
  resources :couriers
  resources :order_bookings do
    collection do
      get "get_warehouse_products"
      get "generate_product_item_form"
      get "add_destination_warehouse"
      get "search_dest_warehouse"
    end
    member do
      get "picking_note"
    end
  end
  resources :account_payables, only: [:new, :create, :index, :destroy, :show] do
    collection do
      get 'generate_form'
      get 'generate_dp_payment_form'
      get 'get_purchase_returns_for_dp'
      get 'select_purchase_return_for_dp'
      post 'create_dp_payment'
      get 'get_received_purchases'
      get 'overdue_invoice_list'
    end
    member do
      get 'print'
    end
  end
  resources :emails
  resources :receiving, only: [:new, :create, :index, :show] do
    get :autocomplete_product_code, :on => :collection
    collection do
      get "get_product_details"
      get "search_do_numbers"
      get "goods_received_not_invoiced"
    end

    member do
      get 'get_purchase_order'
      post 'receive_products_from_purchase_order'
      get 'check_grni'
    end
  end

  resources :purchase_returns, except: [:destroy, :edit, :update] do
    collection do
      get 'get_purchase_order_details'
      get 'get_direct_purchase_details'
      post 'create_direct_purchase_return'
      get 'filter_purchase_records'
    end
    member do
      get 'print'
    end
  end
  resources :stocks, only: :index
  devise_for :users, only: :sessions
  resources :users do
    collection do
      get "generate_spg_user_form"
      get "get_area_manager_info"
    end
  end

  get 'welcome/index'

  resources :purchase_orders do
    get :autocomplete_product_code, :on => :collection
    collection do
      get 'get_product_details'
    end

    member do
      get 'close'
      get 'print'
      get 'export'
    end
  end
  resources :products do
    collection do
      get 'populate_detail_form'
      get 'import'
      post 'import'
    end
  end
  resources :size_groups, except: :show
  resources :sales_promotion_girls
  resources :warehouses do
    collection do
      get 'get_cities'
    end
  end
  resources :price_codes, except: :show
  resources :area_managers do
    member do
      get "get_warehouses"
    end
  end
  resources :vendors
  resources :regions, except: :show
  resources :goods_types, except: :show
  resources :models, except: :show
  resources :colors, except: :show
  resources :brands, except: :show
  resources :cost_prices do
    collection do
      get "generate_form"
      get "autocomplete_product"
      patch "create"
    end
  end

  root 'welcome#index'
  mount ActionCable.server => '/cable'

end

app/controllers/price_lists_controller.rb
class PriceListsController < ApplicationController
  before_action :set_price_list, only: [:show, :edit, :update, :destroy]
  before_action :convert_price_to_numeric, only: [:create, :update]
  before_action :get_products, only: [:new, :edit]

  # GET /price_lists
  # GET /price_lists.json
  def index
    @price_lists = PriceList.joins(product_detail: [:size, :product, :price_code]).select("price_lists.id, effective_date, price, size, products.code as products_code, common_fields.code as price_codes_code")
  end

  # GET /price_lists/1
  # GET /price_lists/1.json
  def show
  end

  # GET /price_lists/new
  def new
  end

  # GET /price_lists/1/edit
  def edit
    @product = Product.select(:id, :code, :size_group_id).where(id: @price_list.products_id).first
    @sizes = Size.joins(:size_group).select("sizes.id, size").where(size_group_id: @product.size_group_id)
    @price_codes = PriceCode.select :id, :code
    @price_list.product_id = @product.id
    @price_list.effective_date = @price_list.effective_date.strftime("%d/%m/%Y") if @price_list.effective_date
    # dua kode dibawah seharusnya tidak usah, cuma ada bug, rails tidak bisa ambil dua field dibawah hasil innerjoin
    @price_list.size_id = @price_list[:size_id]
    @price_list.price_code_id = @price_list[:price_code_id]
  end

  # POST /price_lists
  # POST /price_lists.json
  def create
    @price_list = PriceList.new(price_list_params)
    @price_list.user_is_adding_new_price = true

    respond_to do |format|
      begin
        if @price_list.save
          format.html { redirect_to price_lists_url, notice: 'Price was successfully created.' }
          format.json { render :show, status: :created, location: @price_list }
        else
          get_products
          @product = Product.select(:id, :code, :size_group_id).where(id: params[:price_list][:product_id]).limit(1).first
          @sizes = Size.joins(:size_group).select("sizes.id, size").where(size_group_id: @product.size_group_id)
          @price_codes = PriceCode.select :id, :code
          format.html { render :new }
          format.json { render json: @price_list.errors, status: :unprocessable_entity }
        end
      rescue ActiveRecord::RecordNotUnique => e
        get_products
        @product = Product.select(:id, :code, :size_group_id).where(id: params[:price_list][:product_id]).limit(1).first
        @sizes = Size.joins(:size_group).select("sizes.id, size").where(size_group_id: @product.size_group_id)
        @price_codes = PriceCode.select :id, :code
        unless e.message.include?("price_lists.effective_date, price_lists.product_detail_id")
          @price_list.errors.messages[:product_id] = @price_list.errors.messages[:size_id] = @price_list.errors.messages[:price_code_id] = ["has already been taken"]
        else
          @price_list.errors.messages[:product_id] = @price_list.errors.messages[:effective_date] = @price_list.errors.messages[:size_id] = @price_list.errors.messages[:price_code_id] = ["has already been taken"]
        end
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /price_lists/1
  # PATCH/PUT /price_lists/1.json
  def update
    respond_to do |format|
      begin
        if @price_list.update(price_list_params)
          format.html { redirect_to price_lists_url, notice: 'Price was successfully updated.' }
          format.json { render :show, status: :ok, location: @price_list }
        else
          get_products
          @product = Product.select(:id, :code, :size_group_id).where(id: @price_list.products_id).first
          @sizes = Size.joins(:size_group).select("sizes.id, size").where(size_group_id: @product.size_group_id)
          @price_codes = PriceCode.select :id, :code
          format.html { render :edit }
          format.json { render json: @price_list.errors, status: :unprocessable_entity }
        end
      rescue ActiveRecord::RecordNotUnique => e
        get_products
        @price_list.errors.messages[:effective_date] = ["has already been taken"]
        format.html { render :edit }
      end
    end
  end

  # DELETE /price_lists/1
  # DELETE /price_lists/1.json
  def destroy
    @price_list.user_is_deleting_from_child = true
    unless @price_list.destroy
      alert = @price_list.errors.messages[:base].to_sentence
    else
      notice = "Price was successfully deleted."
    end
    respond_to do |format|
      format.html do 
        if notice.present?
          redirect_to price_lists_url, notice: notice
        else
          redirect_to price_lists_url, alert: alert
        end
      end
      format.json { head :no_content }
    end
  end
  
  def generate_price_form
    @price_list = PriceList.new product_id: params[:id]
    @product = Product.select(:id, :code, :size_group_id).where(id: params[:id]).limit(1).first
    @sizes = Size.joins(:size_group).select("sizes.id, size").where(size_group_id: @product.size_group_id)
    @price_codes = PriceCode.select :id, :code
    respond_to { |format| format.js }
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_price_list
    @price_list = PriceList.joins(product_detail: [:size, :product, :price_code]).select("price_lists.id, price, products.id as products_id, products.code, effective_date, size_id, price_code_id, size, common_fields.code as price_code, product_detail_id").where(id: params[:id]).first
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def price_list_params
    unless params[:action].eql?("update")
      params.require(:price_list).permit(:effective_date, :price, :product_id, :size_id, :price_code_id)
    else
      params.require(:price_list).permit(:effective_date, :price, :product_id, :size_id, :price_code_id).merge(user_is_updating_price: true)
    end
  end
    
  def get_products
    @products = Product.joins(:brand, :model, :goods_type, :vendor).select("products.id, products.code as products_code, common_fields.name, models_products.name as models_products_name, goods_types_products.name as goods_types_products_name, vendors.name as vendors_name, target")
  end
  
  def convert_price_to_numeric
    params[:price_list][:price] = params[:price_list][:price].gsub("Rp","").gsub(".","").gsub(",",".")
  end
end

app/helpers/price_lists_helper.rb
module PriceListsHelper
end

app/views/price_lists/_form.html.erb
<div class="form-horizontal">
    <div class="form-group">
        <label class="col-sm-2 control-label">Select Product</label>
        <div class="col-sm-10">
            <table id="listing_products_table_price_lists" class="display">
                <thead>
                    <tr>
                        <th>Product Code</th>
                        <th>Brand</th>
                        <th>Model</th>
                        <th>Goods Type</th>
                        <th>Vendor</th>
                        <th>Target</th>
                    </tr>
                </thead>

                <tbody>
                    <% @products.each do |product| %>
                      <tr id="listing_products_table_price_lists_<%= product.id %>">
                          <td id="products_code_<%= product.id %>"><%= product.products_code %></td>
                          <td><%= product.name %></td>
                          <td><%= product.models_products_name %></td>
                          <td><%= product.goods_types_products_name %></td>
                          <td><%= product.vendors_name %></td>
                          <td><%= product.target %></td>
                      </tr>
                    <% end %>
                </tbody>
            </table>
            <%= submit_tag "Generate form", id: "generate_price_form", class: "btn btn-default active", style: "float: right;margin-top: 10px;" %>
          </div>
      </div>
      <div id="price_form_container">
          <% if params[:action].eql?("create") || params[:action].eql?("edit") || params[:action].eql?("update") %>
            <%= render partial: "price_form", locals: {f: @price_list} %>
          <% end %>
      </div>
  </div>

  <% if params[:action].eql?("create") || params[:action].eql?("edit") || params[:action].eql?("update") %>
    <script>
      selectedPriceListProductId = '<%= params[:price_list][:product_id] rescue @price_list.products_id %>';
    </script>
  <% end %>

app/views/price_lists/_price_form.html.erb
<%= form_for(@price_list) do |f| %>
  <!--
  <% if @price_list.errors.any? %>
                                            <div id="error_explanation">
                                              <h2><%= pluralize(@price_list.errors.count, "error") %> prohibited this price_list from being saved:</h2>

                                              <ul>
    <% @price_list.errors.full_messages.each do |message| %>
                                                                                      <li><%= message %></li>
    <% end %>
                                              </ul>
                                            </div>
  <% end %>
  -->
  <div class="form-group<%= control_group_error(@price_list, :product_id) %>">
      <%= f.label :product_id, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
            <%= f.hidden_field :product_id %>
            <span class="form-control" disabled="true">
                <%= @product.code rescue @price_list.code %>
            </span>
            <%= error_help_text(@price_list, :product_id) %>
        </div>
    </div>
    <div class="form-group<%= control_group_error(@price_list, :effective_date) %>">
        <%= f.label :effective_date, class: "col-sm-2 control-label" %>
          <div class="col-sm-10">
              <%= f.text_field :effective_date, size: 10, readonly: true, tabindex: "1", class: "form-control" %>
                <%= error_help_text(@price_list, :effective_date) %>
            </div>
        </div>
        <div class="form-group<%= control_group_error(@price_list, :price) %>">
            <%= f.label :price, class: "col-sm-2 control-label" %>
              <div class="col-sm-10">
                  <%= f.text_field :price, tabindex: "2", placeholder: "price", "data-a-sep" => ".",
                    "data-a-dec" => ",", "data-a-sign" => "Rp", style: "text-align:right;", size: 16, class: "form-control" %>
                    <%= error_help_text(@price_list, :price) %>
                </div>
            </div>
            <% if @price_list.new_record? %>
              <div class="form-group<%= control_group_error(@price_list, :size_id) %>">
                  <%= f.label :size_id, class: "col-sm-2 control-label" %>
                    <div class="col-sm-10">
                        <%= f.select :size_id, options_from_collection_for_select(@sizes, :id, :size, @price_list.size_id.to_s), {prompt: true}, {tabindex: "3", class: "form-control"} %>
                          <%= error_help_text(@price_list, :size_id) %>
                      </div>
                  </div>
                  <div class="form-group<%= control_group_error(@price_list, :price_code_id) %>">
                      <%= f.label :price_code_id, class: "col-sm-2 control-label" %>
                        <div class="col-sm-10">
                            <%= f.select :price_code_id, options_from_collection_for_select(@price_codes, :id, :code, @price_list.price_code_id.to_s), {prompt: true}, {tabindex: "4", class: "form-control"} %>
                              <%= error_help_text(@price_list, :price_code_id) %>
                          </div>
                      </div>
                    <% else %>
                      <div class="form-group">
                          <%= f.label :size_id, class: "col-sm-2 control-label" %>
                            <div class="col-sm-10">
                                <span class="form-control" disabled="true">
                                    <%= @price_list.size %>
                                </span>
                            </div>
                        </div>
                        <div class="form-group">
                            <%= f.label :price_code_id, class: "col-sm-2 control-label" %>
                              <div class="col-sm-10">
                                  <span class="form-control" disabled="true">
                                      <%= @price_list.price_code %>
                                  </span>
                              </div>
                          </div>
                        <% end %>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <%= f.submit "Save", class: "btn btn-default active" %>
                              </div>
                          </div>
                        <% end %>

app/views/price_lists/edit.html.erb
<div class="page-header"><h1>Editing Price</h1></div>

<%= render 'form' %>

app/views/price_lists/generate_price_form.js.erb
$("#price_form_container").html("<%= j(render(partial: "price_form", locals: {f: @price_list})) %>");
$("#price_list_effective_date").datepicker({
  dateFormat: "dd/mm/yy"
});
$('#price_list_price').autoNumeric('init');

app/views/price_lists/index.html.erb
<div class="page-header">
    <h1>Prices</h1>
</div>

<table class="table table-condensed table-responsive table-striped">
    <thead>
        <tr>
            <th>Product Code</th>
            <th>Size</th>
            <th>Price</th>
            <th>Price Code</th>
            <th>Effective Date</th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        <% @price_lists.each do |price_list| %>
          <tr>
              <td><%= price_list.products_code %></td>
              <td><%= price_list.size %></td>
              <td><%= price_list.price %></td>
              <td><%= price_list.price_codes_code %></td>
              <td><%= price_list.effective_date.strftime("%d/%m/%Y") %></td>
              <td>
                  <%= link_to 'Edit', edit_price_list_path(price_list), class: "btn btn-warning btn-xs active" %>
                  <%= link_to 'Destroy', price_list, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs active" %>
              </td>
          </tr>
        <% end %>
    </tbody>
</table>

<%= link_to 'New Price', new_price_list_path, class: "btn btn-default active" %>

app/views/price_lists/new.html.erb
<div class="page-header"><h1>New Price</h1></div>

<%= render 'form' %>

app/views/price_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Effective date:</strong>
  <%= @price_list.effective_date %>
</p>

<p>
  <strong>Price:</strong>
  <%= @price_list.price %>
</p>

<p>
  <strong>Product detail:</strong>
  <%= @price_list.product_detail %>
</p>

<%= link_to 'Edit', edit_price_list_path(@price_list) %> |
<%= link_to 'Back', price_lists_path %>