config/routes.rb
Rails.application.routes.draw do
  resources :print_barcode_temps, only: [:new, :create] do    
    collection do
      get "search_product"
      get "add_product"
    end
  end
  resources :accounts_receivable_payments, except: [:edit, :update, :destroy] do
    collection do
      get "generate_form"
      get "get_account_numbers"
    end
  end
  resources :accounts_receivable_invoices, only: [:index, :show] do
    collection do
      get "customer_debts"
      get 'overdue_invoice_list'
    end
    member do
      get "print"
    end
  end
  resources :account_payable_courier_payments, except: [:edit, :update, :destroy] do
    collection do
      get "generate_form"
      get "get_account_numbers"
    end
    member do
      get "print"
    end
  end
  resources :account_payable_couriers, except: [:edit, :update] do
    collection do
      get "get_packing_lists"
      get 'overdue_invoice_list'
    end
    member do
      get "print"
    end
  end  
  resources :general_variables, except: [:show, :destroy, :index]
  resources :packing_lists, except: [:edit, :update] do
    member do
      get 'print'
    end
    collection do
      get 'get_courier_ways'
      get 'get_courier_units'
      get 'get_courier_price_types'
      get 'get_courier_cities'
      get 'generate_packing_list_item_form'
      get :autocomplete_shipment_number
    end
  end
  resources :courier_prices do
    collection do
      get "get_courier_ways"
      get "get_courier_units"
    end
  end
  resources :account_payable_payments, except: [:edit, :update, :destroy] do
    collection do
      get "generate_form"
      get 'get_purchase_returns'
      get 'select_purchase_return'
      get "get_account_numbers"
    end
    member do
      get "print"
    end
  end
  resources :adjustments, except: [:edit, :update, :destroy] do
    collection do
      get :autocomplete_product_code
      get :get_product
    end
  end
  get 'import_beginning_stocks' => 'import_beginning_stocks#new'

  post 'import_beginning_stocks/create'

  get 'sell_thru' => 'sell_thrus#index'
  get 'quantity_sold_charts/index'
  resources :targets
  get 'growth_reports/index'
  get 'growth_reports/print'
  get 'growth_reports/export'

  namespace :api, defaults: { format: :json } do
    resources :stock_mutations do
      collection do
        get "store_to_store_inventory_receipts"
        get "search"
      end
      member do
        get "receive"
      end
    end
    resources :consignment_sales do
      collection do
        get "get_events"
        get "get_product"
      end
      member do
        get "approve"
        get "unapprove"
      end
    end
    resources :shipments, except: [:edit, :update] do
      collection do
        get "inventory_receipts"
        get "search_do"
      end
      member do
        get "receive"
      end
    end
    devise_for :users, only: :sessions
  end

  resources :customers do
    collection do
      get "get_cities"
    end
  end
  resources :consignment_sales do
    collection do
      get "get_product"
      get "get_product_colors"
      get "get_product_sizes"
      get "get_events"
    end
    member do
      get "approve"
      get "unapprove"
    end
  end
  get 'incompatible_browsers/index'

  resources :sales_returns, except: [:edit, :update, :destroy] do
    collection do
      get "search_receipt"
      get "get_replacement_product"
      get "get_replacement_product_colors"
      get "get_replacement_product_sizes"
    end
  end
  

  resources :counter_events do
    collection do
      get "generate_warehouse_form"
      get "add_products"
      get "add_general_products"
      get "get_warehouse"
    end
    member do
      get "generate_activation_form"
      patch "activate_deactivate"
    end
  end
  resources :companies
  resources :sales, except: [:edit, :update, :destroy] do
    collection do
      get "get_member"
      get "get_product"
      get "get_free_product"
      get "get_product_colors"
      get "get_free_product_colors"
      get "get_product_sizes"
      get "get_free_product_sizes"
      get "get_gift_event_product"
      get "get_gift_event_product_colors"
      get "get_gift_event_product_sizes"
      get 'export'
      get 'get_stock_detail'
      get 'search_product'
    end
    member do
      get "print"
      get "print_return_receipt"
    end
  end
  resources :members
  resources :banks, except: :show
  resources :cash_disbursements, only: [:index, :new, :create]
  resources :cashier_openings, except: [:edit, :update, :destroy] do
    member do
      get "close"
    end
  end
  resources :events do
    collection do
      get :autocomplete_events
      post :new_add_general_products
      post :new_add_products
      get "generate_warehouse_form"
      get "add_products"
      get "add_general_products"
    end
    member do
      get "generate_activation_form"
      patch "activate_deactivate"
    end
  end
  resources :listing_stocks, only: :index do
    collection do
      get :print
    end
  end
  resources :stock_movements, only: :index do
    collection do
      get :print
    end
  end
  resources :fiscal_years
  resources :goods_in_transits, only: [:shipment_goods, :mutation_goods, :returned_goods] do
    collection do
      get "shipment_goods"
      get "mutation_goods"
      get "returned_goods"
    end
    member do
      get "show_shipment_goods"
      get "show_mutation_goods"
      get "show_returned_goods"
    end
  end

  resources :stock_mutations do
    collection do
      get "get_products"
      get "get_saved_products"
      get "index_store_to_warehouse_mutation"
      get "show_store_to_warehouse_mutation"
      get "new_store_to_warehouse_mutation"
      get "store_to_store_inventory_receipts"
      get "store_to_warehouse_inventory_receipts"
      post "create_store_to_warehouse_mutation"
      get "search"
    end
    member do
      get "approve"
      get "show_store_to_store_receipt"
      get "show_store_to_warehouse_receipt"
      get "receive"
      get "receive_to_warehouse"
      get "print_rolling_doc"
      get "print_return_doc"
      delete "delete_store_to_warehouse"
      get "change_receive_date"
    end
  end
  resources :notifications, only: [:index, :show, :destroy, :notify_user] do
    collection do
      get "notify_user"
    end
  end
  resources :available_menus, only: [:new, :create]
  resources :shipments, except: [:edit, :update] do
    collection do
      get "generate_ob_detail"
      get "inventory_receipts"
      get "search_do"
      get :multiprint
      get :direct_sales
    end
    member do
      get "receive"
      get "change_receive_date"
      get "print"
      get "show_direct_sale"
    end
  end
  resources :couriers
  resources :order_bookings do
    collection do
      get "get_warehouse_products"
      get "generate_product_item_form"
      get "add_destination_warehouse"
      get "search_dest_warehouse"
    end
    member do
      get "picking_note"
    end
  end
  resources :account_payables, only: [:new, :create, :index, :destroy, :show] do
    collection do
      get 'generate_form'
      get 'generate_dp_payment_form'
      get 'get_purchase_returns_for_dp'
      get 'select_purchase_return_for_dp'
      post 'create_dp_payment'
      get 'get_received_purchases'
      get 'overdue_invoice_list'
    end
    member do
      get 'print'
    end
  end
  resources :emails
  resources :receiving, only: [:new, :create, :index, :show] do
    get :autocomplete_product_code, :on => :collection
    collection do
      get "get_product_details"
      get "search_do_numbers"
      get "goods_received_not_invoiced"
    end

    member do
      get 'get_purchase_order'
      post 'receive_products_from_purchase_order'
      get 'check_grni'
    end
  end

  resources :purchase_returns, except: [:destroy, :edit, :update] do
    collection do
      get 'get_purchase_order_details'
      get 'get_direct_purchase_details'
      post 'create_direct_purchase_return'
      get 'filter_purchase_records'
    end
    member do
      get 'print'
    end
  end
  resources :stocks, only: :index
  devise_for :users, only: :sessions
  resources :users do
    collection do
      get "generate_spg_user_form"
      get "get_area_manager_info"
    end
  end

  get 'welcome/index'

  resources :purchase_orders do
    get :autocomplete_product_code, :on => :collection
    collection do
      get 'get_product_details'
    end

    member do
      get 'close'
      get 'print'
      get 'export'
    end
  end
  resources :products do
    collection do
      get 'populate_detail_form'
      get 'import'
      post 'import'
    end
  end
  resources :size_groups, except: :show
  resources :sales_promotion_girls
  resources :warehouses do
    collection do
      get 'get_cities'
    end
  end
  resources :price_codes, except: :show
  resources :area_managers do
    member do
      get "get_warehouses"
    end
  end
  resources :vendors
  resources :regions, except: :show
  resources :goods_types, except: :show
  resources :models, except: :show
  resources :colors, except: :show
  resources :brands, except: :show
  resources :cost_prices do
    collection do
      get "generate_form"
      get "autocomplete_product"
      patch "create"
    end
  end

  root 'welcome#index'
  mount ActionCable.server => '/cable'

end

app/models/courier_price.rb
class CourierPrice < ApplicationRecord
  attr_accessor :attr_courier_id, :attr_courier_way_id
	audited associated_with: :courier_unit, on: [:create, :update]

  belongs_to :courier_unit
  belongs_to :city
  has_many :packing_lists, dependent: :restrict_with_error
  has_one :packing_list_relation, -> {select("1 AS one")}, class_name: "PackingList"


  PRICE_TYPES = [
    ["Regular", "Regular"],
    ["Express", "Express"]
  ]
  
  validates :city_id, :effective_date, :price_type, :price, :attr_courier_id, :attr_courier_way_id, :courier_unit_id, presence: true
  validate :city_available, if: proc{|cp| cp.city_id.present? && cp.city_id_changed?}
    validates :effective_date, date: {after_or_equal_to: Proc.new { Date.current }, message: 'must be after or equal to today' }, if: proc {|cp| cp.effective_date.present? && cp.effective_date_changed?}
      validate :price_type_available, if: proc {|cp| cp.price_type.present? && cp.price_type_changed?}
        validates :price, numericality: {greater_than_or_equal_to: 1}, if: proc { |cp| cp.price.present? && cp.price_changed? && cp.price.is_a?(Numeric) }
          validate :courier_available, if: proc{|cp| cp.attr_courier_id.present?}
            validate :via_available, if: proc{|cp| cp.attr_courier_way_id.present?}
              validate :unit_available, if: proc{|cp| cp.courier_unit_id.present? && cp.courier_unit_id_changed?}
                validate :editable, if: proc{|cp| cp.persisted?}
    
                  before_destroy :delete_tracks

                  private
                  
                  def editable
                    errors.add(:base, "The record cannot be edited") if packing_list_relation.present?
                  end
                
                  def unit_available                  
                    errors.add(:courier_unit_id, "does not exist!") if CourierUnit.joins(courier_way: :courier).select("1 AS one").where(id: courier_unit_id).where(["couriers.status = ? AND couriers.id = ? AND courier_ways.id = ?", "External", attr_courier_id, attr_courier_way_id]).blank?
                  end
              
                  def via_available
                    errors.add(:attr_courier_way_id, "does not exist!") if CourierWay.joins(:courier).select("1 AS one").where(id: attr_courier_way_id).where(["couriers.status = ? AND couriers.id = ?", "External", attr_courier_id]).blank?
                  end
            
                  def courier_available
                    errors.add(:attr_courier_id, "does not exist!") if Courier.select("1 AS one").where(status: "External").find(attr_courier_id).blank?
                  end
          
                  def delete_tracks
                    audits.destroy_all
                  end
  
                  def city_available
                    errors.add(:city_id, "does not exist!") if City.select("1 AS one").where(id: city_id).blank?
                  end
      
                  def price_type_available
                    CourierPrice::PRICE_TYPES.select{ |x| x[1] == price_type }.first.first
                  rescue
                    errors.add(:price_type, "does not exist!")
                  end
                end

app/controllers/courier_prices_controller.rb
include SmartListing::Helper::ControllerExtensions
class CourierPricesController < ApplicationController
  helper SmartListing::Helper
  authorize_resource class: Courier
    before_action :set_courier_price, only: [:show, :edit, :update, :destroy]

    # GET /courier_prices
    # GET /courier_prices.json
    def index
      if params[:filter_effective_date].present?
        splitted_effective_date_range = params[:filter_effective_date].split("-")
        start_effective_date = splitted_effective_date_range[0].strip.to_date
        end_effective_date = splitted_effective_date_range[1].strip.to_date
      end

      courier_prices_scope = CourierPrice.select(:id, :effective_date, :price_type, :price, "couriers.code", "couriers.name", "cities.name AS city_name").joins([courier_unit: [courier_way: :courier]], :city).where(["couriers.status = ?", "External"])
      courier_prices_scope = courier_prices_scope.where(["couriers.id = ?", params[:filter_courier]]) if params[:filter_courier].present?
      courier_prices_scope = courier_prices_scope.where(["city_id = ?", params[:filter_city]]) if params[:filter_city].present?
      courier_prices_scope = courier_prices_scope.where(["effective_date BETWEEN ? AND ?", start_effective_date, end_effective_date]) if params[:filter_effective_date].present?
      courier_prices_scope = courier_prices_scope.where(["price_type = ?", params[:filter_price_type]]) if params[:filter_price_type].present?
      smart_listing_create(:courier_prices, courier_prices_scope, partial: 'courier_prices/listing', default_sort: {effective_date: "desc"})
    end

    # GET /courier_prices/1
    # GET /courier_prices/1.json
    def show
    end

    # GET /courier_prices/new
    def new
      @courier_price = CourierPrice.new
    end

    # GET /courier_prices/1/edit
    def edit
      @courier_price.effective_date = @courier_price.effective_date.strftime("%d/%m/%Y")
      @courier_price.attr_courier_id = @courier_price.courier_id
      @courier_price.attr_courier_way_id = @courier_price.courier_way_id
    end

    # POST /courier_prices
    # POST /courier_prices.json
    def create
      convert_price_to_numeric
      @courier_price = CourierPrice.new(courier_price_params)
      @invalid = !@courier_price.save
    rescue ActiveRecord::RecordNotUnique => e
      render js: "bootbox.alert({message: 'Price should be unique!', size: 'small'})"
    end

    # PATCH/PUT /courier_prices/1
    # PATCH/PUT /courier_prices/1.json
    def update
      convert_price_to_numeric
      begin        
        unless @valid = @courier_price.update(courier_price_params)
          if @courier_price.errors[:base].present?
            render js: "bootbox.alert({message: \"#{@courier_price.errors[:base].join("<br/>")}\",size: 'small'});"
          end
        end
      rescue ActiveRecord::RecordNotUnique => e
        @valid = false
        @courier_price.errors.messages[:effective_date] = ["has already been taken"]
      end
    end

    # DELETE /courier_prices/1
    # DELETE /courier_prices/1.json
    def destroy
      unless @courier_price.destroy
        @deleted = false
      else
        @deleted = true
      end
    end
    
    def get_courier_ways
      @courier_ways = CourierWay.select(:id, :name).where(courier_id: params[:courier_id]).order(:name)
    end

    def get_courier_units
      @courier_units = CourierUnit.select(:id, :name).where(courier_way_id: params[:courier_way_id]).order(:name)
    end

    private
    
    def convert_price_to_numeric
      params[:courier_price][:price] = params[:courier_price][:price].gsub("Rp","").gsub(".","").gsub(",",".") if params[:courier_price][:price].present?
    end
  
    # Use callbacks to share common setup or constraints between actions.
    def set_courier_price
      @courier_price = CourierPrice.joins(:city, courier_unit: [courier_way: :courier]).select(:id, :effective_date, :price_type, :price, :city_id, :courier_unit_id, "couriers.code", "couriers.name", "cities.name AS city_name", "courier_ways.name AS via", "courier_units.name AS unit", "courier_ways.courier_id", "courier_units.courier_way_id").find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def courier_price_params
      params.require(:courier_price).permit(:city_id, :effective_date, :price_type, :price, :attr_courier_id, :attr_courier_way_id, :courier_unit_id)
    end
  end

app/helpers/courier_prices_helper.rb
module CourierPricesHelper
end

app/views/courier_prices/_courier_price.html.erb
<td id="courier-price-courier-<%= object.id %>"><%= "#{object.code} - #{object.name}" rescue "" %></td>
<td id="courier-price-city-<%= object.id %>"><%= object.city_name rescue "" %></td>
<td><%= object.effective_date.strftime("%d/%m/%Y") %></td>
<td><%= object.price_type %></td>
<td><%= number_to_currency(object.price,
      :separator => ",",
      :delimiter => ".",
      :unit => "Rp",
      :precision => 2) %></td>
<td class="actions" style="text-align: right">
    <%= link_to "<i class=\"glyphicon glyphicon-share-alt\"></i>".html_safe, courier_price_path(object), data: {remote: true}, title: "Show" %>
    <%= link_to_if(can?(:manage, Courier), content_tag(:i, "", :class => "glyphicon glyphicon-pencil"), edit_courier_price_path(object), :remote => true, class: :edit, :method => :get, title: "Edit" ) %>
      <%= link_to_if(can?(:manage, Courier) && object.packing_list_relation.blank?, content_tag(:i, "", :class => "glyphicon glyphicon-trash"), object, :remote => true, :class => "destroy", :method => :delete, :data => {:confirmation => 'Are you sure that you want to permanently delete the selected item?', placement: :left}, title: "Delete" ) %>
  </td>

app/views/courier_prices/_form.html.erb
<td colspan="6">
    <div style="padding-top: 20px"></div>
    <%= form_for(@courier_price, remote: true, html: {class: "form-horizontal"}) do |f| %>
        <div class="form-group<%= control_group_error(f.object, :attr_courier_id) %>">
            <%= f.label :attr_courier_id, "Courier", class: "col-sm-2 control-label" %>
              <div class="col-sm-10">
                  <%= f.select :attr_courier_id, options_from_collection_for_select(Courier.select(:id, :code, :name).where(status: "External").order(:code), :id, "code_and_name", f.object.attr_courier_id.to_s), {include_blank: true}, {class: "form-control"} %>
                    <%= error_help_text(f.object, :attr_courier_id) %>
                </div>
            </div>
            <%
            courier_ways = if @courier_price.attr_courier_id.present?                          
              options_from_collection_for_select(CourierWay.select(:id, :name).where(courier_id: @courier_price.attr_courier_id).order(:name), :id, :name, @courier_price.attr_courier_way_id.to_s)
              else
              ""
              end
          %>          
            <div class="form-group<%= control_group_error(f.object, :attr_courier_way_id) %>">
                <%= f.label :attr_courier_way_id, "Via", class: "col-sm-2 control-label" %>
                  <div class="col-sm-10">
                      <%= f.select :attr_courier_way_id, courier_ways, {include_blank: true}, {class: "form-control"} %>
                        <%= error_help_text(f.object, :attr_courier_way_id) %>
                    </div>
                </div>
                <%
                courier_units = if @courier_price.attr_courier_way_id.present?                          
                  options_from_collection_for_select(CourierUnit.select(:id, :name).where(courier_way_id: @courier_price.attr_courier_way_id).order(:name), :id, :name, @courier_price.courier_unit_id.to_s)
                  else
                  ""
                  end
              %>          
                <div class="form-group<%= control_group_error(f.object, :courier_unit_id) %>">
                    <%= f.label :courier_unit_id, "Unit", class: "col-sm-2 control-label" %>
                      <div class="col-sm-10">
                          <%= f.select :courier_unit_id, courier_units, {include_blank: true}, {class: "form-control"} %>
                            <%= error_help_text(f.object, :courier_unit_id) %>
                        </div>
                    </div>
                    <div class="form-group<%= control_group_error(f.object, :city_id) %>">
                        <%= f.label :city_id, class: "col-sm-2 control-label" %>
                          <div class="col-sm-10">
                              <%= f.select :city_id, options_from_collection_for_select(City.select(:id, :name).order(:name), :id, :name, f.object.city_id.to_s), {include_blank: true}, {class: "form-control"} %>
                                <%= error_help_text(f.object, :city_id) %>
                            </div>
                        </div>

                        <div class="form-group<%= control_group_error(f.object, :effective_date) %>">
                            <%= f.label :effective_date, class: "col-sm-2 control-label" %>
                              <div class="col-sm-10">
                                  <%= f.text_field :effective_date, readonly: true, class: "form-control" %>
                                    <%= error_help_text(f.object, :effective_date) %>
                                </div>
                            </div>

                            <div class="form-group<%= control_group_error(f.object, :price_type) %>">
                                <%= f.label :price_type, class: "col-sm-2 control-label" %>
                                  <div class="col-sm-10">
                                      <%= f.select :price_type, options_for_select(CourierPrice::PRICE_TYPES, f.object.price_type), {include_blank: true}, {class: "form-control"} %>
                                        <%= error_help_text(f.object, :price_type) %>
                                    </div>
                                </div>

                                <div class="form-group<%= control_group_error(f.object, :price) %>">
                                    <%= f.label :price, class: "col-sm-2 control-label" %>
                                      <div class="col-sm-10">
                                          <%= f.text_field :price, class: "form-control money-fields", "data-a-sep" => ".",
                                              "data-a-dec" => ",", "data-a-sign" => "Rp" %>
                                            <%= error_help_text(f.object, :price) %>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="col-sm-offset-2 col-sm-10">
                                            <%= f.submit "Save", class: "btn btn-primary" %>
                                              <button class="btn btn-link cancel">Cancel</button>
                                          </div>
                                      </div>
                                    <% end %>
                                </td>

                                <script>
                                  $(function () {
                                      if ($("#courier_price_attr_courier_id").length > 0)
                                          $("#courier_price_attr_courier_id").attr("data-placeholder", "Please select").chosen();
                                      $("#courier_price_attr_courier_way_id").attr("data-placeholder", "Please select").chosen();
                                      $("#courier_price_courier_unit_id").attr("data-placeholder", "Please select").chosen();
                                      $("#courier_price_city_id").attr("data-placeholder", "Please select").chosen();
                                      $("#courier_price_price_type").attr("data-placeholder", "Please select").chosen();
                                      $("#courier_price_effective_date").datepicker({
                                          dateFormat: "dd/mm/yy"
                                      });
                                      $('#courier_price_price').autoNumeric('init');
                                      $("#courier_price_attr_courier_id").change(function () {
                                          $.get("/courier_prices/get_courier_ways", {
                                              courier_id: $("#courier_price_attr_courier_id").val()
                                          });
                                      });
                                      $("#courier_price_attr_courier_way_id").change(function () {
                                          $.get("/courier_prices/get_courier_units", {
                                              courier_way_id: $("#courier_price_attr_courier_way_id").val()
                                          });
                                      });
                                  })
                                </script>

app/views/courier_prices/_listing.html.erb
<table class="table table-striped" style="table-layout: fixed;word-wrap: break-word;">
    <thead id="listing-courier-price-thead">
        <tr>
            <th class="col-md-3"><%= smart_listing.sortable "Courier", "code" %></th>
            <th class="col-md-2"><%= smart_listing.sortable "City", "city_name" %></th>
            <th class="col-md-2"><%= smart_listing.sortable "Effective date", "effective_date" %></th>
            <th class="col-md-2"><%= smart_listing.sortable "Price type", "price_type" %></th>
            <th class="col-md-2"><%= smart_listing.sortable "Price", "price" %></th>
            <th class="col-md-1"></th>
        </tr>
    </thead>
    <tbody>
        <% smart_listing.collection.each do |courier_price| %>
          <tr class="editable" data-id="<%= courier_price.id %>">
              <%= smart_listing.render object: courier_price, partial: "courier_prices/courier_price", locals: {object: courier_price} %>
          </tr>
        <% end %>
        <%= smart_listing.item_new colspan: 6, link: new_courier_price_path %>
    </tbody>
</table>
<%= smart_listing.paginate %>
<script>
  var processId = setInterval(function () {
      if ($("#listing-courier-price-thead").is(":visible")) {
          clearInterval(processId);
      } else {
          $("#listing-courier-price-thead").show();
      }
  }, 0);

</script>

app/views/courier_prices/_show.html.erb
<td colspan="6">
    <button type="button" class="close cancel" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <div style="padding-top: 20px"></div>

    <dl class="dl-horizontal">
        <dt>Courier</dt>
        <dd><%= "#{object.code} - #{object.name}" %></dd>
    </dl>   

    <dl class="dl-horizontal">
        <dt>Via</dt>
        <dd><%= object.via %></dd>
    </dl>   

    <dl class="dl-horizontal">
        <dt>Unit</dt>
        <dd><%= object.unit %></dd>
    </dl>   

    <dl class="dl-horizontal">
        <dt>City</dt>
        <dd><%= object.city_name %></dd>
    </dl>

    <dl class="dl-horizontal">
        <dt>Effective date</dt>
        <dd><%= object.effective_date.strftime("%d/%m/%Y") %></dd>
    </dl>

    <dl class="dl-horizontal">
        <dt>Price type</dt>
        <dd><%= object.price_type %></dd>
    </dl>

    <dl class="dl-horizontal">
        <dt>Price</dt>
        <dd><%= number_to_currency(object.price,
              :separator => ",",
              :delimiter => ".",
              :unit => "Rp",
              :precision => 2) %></dd>
    </dl>

</td>

app/views/courier_prices/create.js.erb
<% if @invalid %>
  <%= smart_listing_item :courier_prices, :create, @courier_price, "courier_prices/form" %>
<% else %>
  <%= smart_listing_item :courier_prices, :create, @courier_price, "courier_prices/courier_price" %>
  <% courier_unit = CourierUnit.joins(courier_way: :courier).select("couriers.code", "couriers.name").find(@courier_price.courier_unit_id) %>
  $("#courier-price-courier-<%= @courier_price.id %>").html("<%= "#{courier_unit.code} - #{courier_unit.name}" %>");
  $("#courier-price-city-<%= @courier_price.id %>").html("<%= City.select(:name).find(@courier_price.city_id).name %>");
<% end %>

app/views/courier_prices/destroy.js.erb
<% if @deleted %>
  <%= smart_listing_item :courier_prices, :destroy, @courier_price %>
<% else %>
  <% if @courier_price.errors[:base].present? %>
    bootbox.alert({message: "<%= @courier_price.errors[:base].join("<br/>") %>",size: 'small'});
  <% end %>
<% end %>

app/views/courier_prices/edit.html.erb
<h1>Editing Courier Price</h1>

<%= render 'form', courier_price: @courier_price %>

<%= link_to 'Show', @courier_price %> |
<%= link_to 'Back', courier_prices_path %>

app/views/courier_prices/edit.js.erb
<%= smart_listing_item :courier_prices, :edit, @courier_price, "courier_prices/form" %>

app/views/courier_prices/get_courier_units.js.erb
$('#courier_price_courier_unit_id').find('option').remove();
var o = new Option("", "");
$("#courier_price_courier_unit_id").append(o);
<% @courier_units.each do |courier_unit| %>
  var o = new Option("<%= courier_unit.name %>", "<%= courier_unit.id %>");
  $("#courier_price_courier_unit_id").append(o);
<% end %>
$("#courier_price_courier_unit_id").attr("data-placeholder", "Please select").chosen("destroy").chosen();

app/views/courier_prices/get_courier_ways.js.erb
$('#courier_price_attr_courier_way_id').find('option').remove();
$('#courier_price_courier_unit_id').find('option').remove();
var o = new Option("", "");
$("#courier_price_attr_courier_way_id").append(o);
var o = new Option("", "");
$("#courier_price_courier_unit_id").append(o);
<% @courier_ways.each do |courier_way| %>
  var o = new Option("<%= courier_way.name %>", "<%= courier_way.id %>");
  $("#courier_price_attr_courier_way_id").append(o);
<% end %>
$("#courier_price_attr_courier_way_id").attr("data-placeholder", "Please select").chosen("destroy").chosen();
$("#courier_price_courier_unit_id").attr("data-placeholder", "Please select").chosen("destroy").chosen();

app/views/courier_prices/index.js.erb
<%= smart_listing_update(:courier_prices) %>

app/views/courier_prices/new.js.erb
<%= smart_listing_item :courier_prices, :new, @courier_price, "courier_prices/form" %>

app/views/courier_prices/update.js.erb
<% if @valid %>
  <%= smart_listing_item :courier_prices, :update, @courier_price, "courier_prices/courier_price" %>
  <% courier_unit = CourierUnit.joins(courier_way: :courier).select("couriers.code", "couriers.name").find(@courier_price.courier_unit_id) %>
  $("#courier-price-courier-<%= @courier_price.id %>").html("<%= "#{courier_unit.code} - #{courier_unit.name}" %>");
  $("#courier-price-city-<%= @courier_price.id %>").html("<%= City.select(:name).find(@courier_price.city_id).name %>");
<% else %>
  <%= smart_listing_item :courier_prices, :edit, @courier_price, "courier_prices/form" %>
<% end %>