config/routes.rb
Rails.application.routes.draw do
  resources :print_barcode_temps, only: [:new, :create] do    
    collection do
      get "search_product"
      get "add_product"
    end
  end
  resources :accounts_receivable_payments, except: [:edit, :update, :destroy] do
    collection do
      get "generate_form"
      get "get_account_numbers"
    end
  end
  resources :accounts_receivable_invoices, only: [:index, :show] do
    collection do
      get "customer_debts"
      get 'overdue_invoice_list'
    end
    member do
      get "print"
    end
  end
  resources :account_payable_courier_payments, except: [:edit, :update, :destroy] do
    collection do
      get "generate_form"
      get "get_account_numbers"
    end
    member do
      get "print"
    end
  end
  resources :account_payable_couriers, except: [:edit, :update] do
    collection do
      get "get_packing_lists"
      get 'overdue_invoice_list'
    end
    member do
      get "print"
    end
  end  
  resources :general_variables, except: [:show, :destroy, :index]
  resources :packing_lists, except: [:edit, :update] do
    member do
      get 'print'
    end
    collection do
      get 'get_courier_ways'
      get 'get_courier_units'
      get 'get_courier_price_types'
      get 'get_courier_cities'
      get 'generate_packing_list_item_form'
      get :autocomplete_shipment_number
    end
  end
  resources :courier_prices do
    collection do
      get "get_courier_ways"
      get "get_courier_units"
    end
  end
  resources :account_payable_payments, except: [:edit, :update, :destroy] do
    collection do
      get "generate_form"
      get 'get_purchase_returns'
      get 'select_purchase_return'
      get "get_account_numbers"
    end
    member do
      get "print"
    end
  end
  resources :adjustments, except: [:edit, :update, :destroy] do
    collection do
      get :autocomplete_product_code
      get :get_product
    end
  end
  get 'import_beginning_stocks' => 'import_beginning_stocks#new'

  post 'import_beginning_stocks/create'

  get 'sell_thru' => 'sell_thrus#index'
  get 'quantity_sold_charts/index'
  resources :targets
  get 'growth_reports/index'
  get 'growth_reports/print'
  get 'growth_reports/export'

  namespace :api, defaults: { format: :json } do
    resources :stock_mutations do
      collection do
        get "store_to_store_inventory_receipts"
        get "search"
      end
      member do
        get "receive"
      end
    end
    resources :consignment_sales do
      collection do
        get "get_events"
        get "get_product"
      end
      member do
        get "approve"
        get "unapprove"
      end
    end
    resources :shipments, except: [:edit, :update] do
      collection do
        get "inventory_receipts"
        get "search_do"
      end
      member do
        get "receive"
      end
    end
    devise_for :users, only: :sessions
  end

  resources :customers do
    collection do
      get "get_cities"
    end
  end
  resources :consignment_sales do
    collection do
      get "get_product"
      get "get_product_colors"
      get "get_product_sizes"
      get "get_events"
    end
    member do
      get "approve"
      get "unapprove"
    end
  end
  get 'incompatible_browsers/index'

  resources :sales_returns, except: [:edit, :update, :destroy] do
    collection do
      get "search_receipt"
      get "get_replacement_product"
      get "get_replacement_product_colors"
      get "get_replacement_product_sizes"
    end
  end
  

  resources :counter_events do
    collection do
      get "generate_warehouse_form"
      get "add_products"
      get "add_general_products"
      get "get_warehouse"
    end
    member do
      get "generate_activation_form"
      patch "activate_deactivate"
    end
  end
  resources :companies
  resources :sales, except: [:edit, :update, :destroy] do
    collection do
      get "get_member"
      get "get_product"
      get "get_free_product"
      get "get_product_colors"
      get "get_free_product_colors"
      get "get_product_sizes"
      get "get_free_product_sizes"
      get "get_gift_event_product"
      get "get_gift_event_product_colors"
      get "get_gift_event_product_sizes"
      get 'export'
      get 'get_stock_detail'
      get 'search_product'
    end
    member do
      get "print"
      get "print_return_receipt"
    end
  end
  resources :members
  resources :banks, except: :show
  resources :cash_disbursements, only: [:index, :new, :create]
  resources :cashier_openings, except: [:edit, :update, :destroy] do
    member do
      get "close"
    end
  end
  resources :events do
    collection do
      get :autocomplete_events
      post :new_add_general_products
      post :new_add_products
      get "generate_warehouse_form"
      get "add_products"
      get "add_general_products"
    end
    member do
      get "generate_activation_form"
      patch "activate_deactivate"
    end
  end
  resources :listing_stocks, only: :index do
    collection do
      get :print
    end
  end
  resources :stock_movements, only: :index do
    collection do
      get :print
    end
  end
  resources :fiscal_years
  resources :goods_in_transits, only: [:shipment_goods, :mutation_goods, :returned_goods] do
    collection do
      get "shipment_goods"
      get "mutation_goods"
      get "returned_goods"
    end
    member do
      get "show_shipment_goods"
      get "show_mutation_goods"
      get "show_returned_goods"
    end
  end

  resources :stock_mutations do
    collection do
      get "get_products"
      get "get_saved_products"
      get "index_store_to_warehouse_mutation"
      get "show_store_to_warehouse_mutation"
      get "new_store_to_warehouse_mutation"
      get "store_to_store_inventory_receipts"
      get "store_to_warehouse_inventory_receipts"
      post "create_store_to_warehouse_mutation"
      get "search"
    end
    member do
      get "approve"
      get "show_store_to_store_receipt"
      get "show_store_to_warehouse_receipt"
      get "receive"
      get "receive_to_warehouse"
      get "print_rolling_doc"
      get "print_return_doc"
      delete "delete_store_to_warehouse"
      get "change_receive_date"
    end
  end
  resources :notifications, only: [:index, :show, :destroy, :notify_user] do
    collection do
      get "notify_user"
    end
  end
  resources :available_menus, only: [:new, :create]
  resources :shipments, except: [:edit, :update] do
    collection do
      get "generate_ob_detail"
      get "inventory_receipts"
      get "search_do"
      get :multiprint
      get :direct_sales
    end
    member do
      get "receive"
      get "change_receive_date"
      get "print"
      get "show_direct_sale"
    end
  end
  resources :couriers
  resources :order_bookings do
    collection do
      get "get_warehouse_products"
      get "generate_product_item_form"
      get "add_destination_warehouse"
      get "search_dest_warehouse"
    end
    member do
      get "picking_note"
    end
  end
  resources :account_payables, only: [:new, :create, :index, :destroy, :show] do
    collection do
      get 'generate_form'
      get 'generate_dp_payment_form'
      get 'get_purchase_returns_for_dp'
      get 'select_purchase_return_for_dp'
      post 'create_dp_payment'
      get 'get_received_purchases'
      get 'overdue_invoice_list'
    end
    member do
      get 'print'
    end
  end
  resources :emails
  resources :receiving, only: [:new, :create, :index, :show] do
    get :autocomplete_product_code, :on => :collection
    collection do
      get "get_product_details"
      get "search_do_numbers"
      get "goods_received_not_invoiced"
    end

    member do
      get 'get_purchase_order'
      post 'receive_products_from_purchase_order'
      get 'check_grni'
    end
  end

  resources :purchase_returns, except: [:destroy, :edit, :update] do
    collection do
      get 'get_purchase_order_details'
      get 'get_direct_purchase_details'
      post 'create_direct_purchase_return'
      get 'filter_purchase_records'
    end
    member do
      get 'print'
    end
  end
  resources :stocks, only: :index
  devise_for :users, only: :sessions
  resources :users do
    collection do
      get "generate_spg_user_form"
      get "get_area_manager_info"
    end
  end

  get 'welcome/index'

  resources :purchase_orders do
    get :autocomplete_product_code, :on => :collection
    collection do
      get 'get_product_details'
    end

    member do
      get 'close'
      get 'print'
      get 'export'
    end
  end
  resources :products do
    collection do
      get 'populate_detail_form'
      get 'import'
      post 'import'
    end
  end
  resources :size_groups, except: :show
  resources :sales_promotion_girls
  resources :warehouses do
    collection do
      get 'get_cities'
    end
  end
  resources :price_codes, except: :show
  resources :area_managers do
    member do
      get "get_warehouses"
    end
  end
  resources :vendors
  resources :regions, except: :show
  resources :goods_types, except: :show
  resources :models, except: :show
  resources :colors, except: :show
  resources :brands, except: :show
  resources :cost_prices do
    collection do
      get "generate_form"
      get "autocomplete_product"
      patch "create"
    end
  end

  root 'welcome#index'
  mount ActionCable.server => '/cable'

end

app/helpers/account_payables_helper.rb
module AccountPayablesHelper
  def get_second_discount_in_money_for_ap(purchase_order)
    if purchase_order.is_additional_disc_from_net
      value_from_first_discount = purchase_order.receiving_value - purchase_order.receiving_value * (purchase_order.first_discount.to_f / 100)
      value_from_first_discount * (purchase_order.second_discount.to_f / 100)
    else
      purchase_order.receiving_value * (purchase_order.second_discount.to_f / 100)
    end
  end
  
  def get_vat_in_money_for_ap(purchase_order)
    value_after_discount_for_ap(purchase_order) * 0.1
  end

  def get_include_vat_in_money_for_ap(purchase_order)
    (value_after_discount_for_ap(purchase_order) / 1.1 * 0.1).round(2)
  end
  
  def value_after_discount_for_ap(purchase_order)
    value_after_first_discount = purchase_order.receiving_value - purchase_order.receiving_value * (purchase_order.first_discount.to_f / 100)
    value_after_second_discount = if purchase_order.is_additional_disc_from_net
      value_after_first_discount - value_after_first_discount * (purchase_order.second_discount.to_f / 100)
    elsif purchase_order.second_discount.present?
      purchase_order.receiving_value - purchase_order.receiving_value * ((purchase_order.first_discount.to_f + purchase_order.second_discount.to_f) / 100)
    end
    return value_after_second_discount || value_after_first_discount
  end
  
  def value_after_ppn_for_ap(purchase_order)
    vat_type = purchase_order.value_added_tax rescue purchase_order.vat_type
    if vat_type.eql?("exclude")
      value_after_discount_for_ap(purchase_order) + get_vat_in_money_for_ap(purchase_order)
    else
      value_after_discount_for_ap(purchase_order)
    end
  end
  
  def get_second_discount_in_money_for_ap_partial(received_purchase_order, purchase_type, gross_amount)
    if purchase_type.eql?("order")
      if received_purchase_order.po_is_additional_disc_from_net == true
        value_from_first_discount = gross_amount - (received_purchase_order.po_first_discount.to_f / 100) * gross_amount
        value_from_first_discount * (received_purchase_order.po_second_discount.to_f / 100)
      else
        gross_amount * (received_purchase_order.po_second_discount.to_f / 100)
      end
    else
      if received_purchase_order.dp_is_additional_disc_from_net == true
        value_from_first_discount = gross_amount - (received_purchase_order.dp_first_discount.to_f / 100) * gross_amount
        value_from_first_discount * (received_purchase_order.dp_second_discount.to_f / 100)
      else
        gross_amount * (received_purchase_order.dp_second_discount.to_f / 100)
      end
    end
  end
  
  def get_include_vat_in_money_for_ap_partial(received_purchase_order, purchase_type, gross_amount)
    (value_after_discount_for_ap_partial(received_purchase_order, purchase_type, gross_amount) / 1.1 * 0.1).round(2)
  end
  
  def value_after_discount_for_ap_partial(received_purchase_order, purchase_type, gross_amount)
    if purchase_type.eql?("order")
      value_after_first_discount = gross_amount - gross_amount * (received_purchase_order.po_first_discount.to_f / 100)
      value_after_second_discount = if received_purchase_order.po_is_additional_disc_from_net == true
        value_after_first_discount - value_after_first_discount * (received_purchase_order.po_second_discount.to_f / 100)
      elsif received_purchase_order.po_second_discount.present?
        gross_amount - gross_amount * ((received_purchase_order.po_first_discount.to_f + received_purchase_order.po_second_discount.to_f) / 100)
      end
      return value_after_second_discount || value_after_first_discount
    else
      value_after_first_discount = gross_amount - gross_amount * (received_purchase_order.dp_first_discount.to_f / 100)
      value_after_second_discount = if received_purchase_order.dp_is_additional_disc_from_net == true
        value_after_first_discount - value_after_first_discount * (received_purchase_order.dp_second_discount.to_f / 100)
      elsif received_purchase_order.dp_second_discount.present?
        gross_amount - gross_amount * ((received_purchase_order.dp_first_discount.to_f + received_purchase_order.dp_second_discount.to_f) / 100)
      end
      return value_after_second_discount || value_after_first_discount
    end
  end
  
  def get_vat_in_money_for_ap_partial(received_purchase_order, purchase_type, gross_amount)
    value_after_discount_for_ap_partial(received_purchase_order, purchase_type, gross_amount) * 0.1
  end
  
  def value_after_ppn_for_ap_partial(received_purchase_order, purchase_type, gross_amount)
    vat_type = if purchase_type.eql?("order")
      received_purchase_order.po_vat_type
    else
      received_purchase_order.dp_vat_type
    end
    if vat_type.eql?("exclude")
      value_after_discount_for_ap_partial(received_purchase_order, purchase_type, gross_amount) + get_vat_in_money_for_ap_partial(received_purchase_order, purchase_type, gross_amount)
    else
      value_after_discount_for_ap_partial(received_purchase_order, purchase_type, gross_amount)
    end
  end

end

app/views/account_payables/_account_payable.html.erb
<td class="text-center"><%= object.number %></td>
<td class="text-center" id="vendor_name_<%= object.id %>"><%= object.name rescue "" %></td>
<td class="text-center"><%= object.vendor_invoice_number %></td>
<td class="text-center"><%= object.vendor_invoice_date.strftime("%d/%m/%Y") %></td>
<td class="text-center"><%= object.due_date.strftime("%d/%m/%Y") rescue "" %></td>
<td class="text-center"><%= number_to_currency(object.total,
      :separator => ",",
      :delimiter => ".",
      :unit => "Rp",
      :precision => 2) %></td>
<td class="text-center"><%= number_to_currency(object.remaining_debt,
      :separator => ",",
      :delimiter => ".",
      :unit => "Rp",
      :precision => 2) %></td>
<td class="actions text-center" style="text-align: right">
    <%= link_to "<i class=\"glyphicon glyphicon-share-alt\"></i>".html_safe, account_payable_path(object), data: {remote: true}, id: "show_detail_ap_#{object.id}", title: "Show" %>
    <% unless action_name.eql?("overdue_invoice_list") %>
      <%= link_to_if(can?(:manage, AccountPayable), content_tag(:i, "", :class => "glyphicon glyphicon-print"), print_account_payable_path(object), :remote => true, :method => :get, title: "Print" ) %>
      <%= link_to_if(can?(:manage, AccountPayable) && object.account_payable_payment_invoices.select("1 AS one").blank?, content_tag(:i, "", :class => "glyphicon glyphicon-trash"), object, :remote => true, :class => "destroy", :method => :delete, :data => {:confirmation => 'Are you sure that you want to permanently delete the selected item?', placement: :left}, title: "Delete" ) %>
    <% end %>
</td>

app/views/account_payables/_listing.html.erb
<table class="table table-striped" style="table-layout: fixed;word-wrap: break-word;">
    <thead id="listing-ap-thead">
        <tr>
            <th class="col-md-2 text-center" rowspan="2" style="vertical-align: middle"><%= smart_listing.sortable "Number", "number" %></th>
            <th class="col-md-4 text-center" colspan="3">Vendor</th>
            <th class="col-md-1 text-center" rowspan="2" style="vertical-align: middle"><%= smart_listing.sortable "Due Dt", "due_date" %></th>
            <th class="col-md-2 text-center" rowspan="2" style="vertical-align: middle"><%= smart_listing.sortable "Total", "total" %></th>
            <th class="col-md-2 text-center" rowspan="2" style="vertical-align: middle"><%= smart_listing.sortable "Rem. Debt", "remaining_debt" %></th>
            <th class="col-md-1 text-center" rowspan="2" style="vertical-align: middle"></th>
        </tr>
        <tr>
            <th class="col-md-4 text-center"><%= smart_listing.sortable "Name", "vendors.name" %></th>
            <th class="col-md-4 text-center"><%= smart_listing.sortable "Inv. Number", "vendor_invoice_number" %></th>
            <th class="col-md-4 text-center"><%= smart_listing.sortable "Inv. Date", "vendor_invoice_date" %></th>
        </tr>
    </thead>
    <tbody>
        <% smart_listing.collection.each do |ap| %>
          <tr class="editable" data-id="<%= ap.id %>">
              <%= smart_listing.render object: ap, partial: "account_payables/account_payable", locals: {object: ap} %>
          </tr>
        <% end %>
        <% unless action_name.eql?("overdue_invoice_list") %>
          <%= smart_listing.item_new colspan: 8, link: new_account_payable_path %>
        <% end %>
    </tbody>
</table>
<%= smart_listing.paginate %>
<script>
  var processId = setInterval(function () {
      if ($("#listing-ap-thead").is(":visible")) {
          clearInterval(processId);
      } else {
          $("#listing-ap-thead").show();
      }
  }, 0);

</script>

app/views/account_payables/_payment_form_for_dp.html.erb
<% total_amount_received_for_dp = 0 %>
<%= form_for(@account_payable, url: create_dp_payment_account_payables_path, remote: true, html: {class: "form-horizontal", style: "padding-top: 20px"}) do |f| %>
    <%= f.hidden_field :vendor_id, id: "account_payable_vendor_id_for_dp" %>
    <div class="form-group<%= control_group_error(@account_payable, :total) %>">
        <label class="col-sm-2 control-label">Direct Purchases</label>
        <div class="col-sm-10">              
            <table class="table">
                <thead>
                    <tr>
                        <th>Number</th>
                        <th>Qty</th>
                        <th>Gross Amount</th>
                        <th>1st Disc</th>
                        <th>2nd Disc</th>
                        <th>Value Added Tax (10%)</th>
                        <th>Net Amount</th>
                    </tr>
                </thead>
                <tbody>
                    <%= f.fields_for :account_payable_purchases do |account_payable_purchase_form| %>
                      <%= account_payable_purchase_form.hidden_field :purchase_id, class: "direct-purchase-ids" %>
                        <%= account_payable_purchase_form.hidden_field :purchase_type %>
                        <% direct_purchase = account_payable_purchase_form.object.purchase %>
                        <tr id="direct_purchase_<%= direct_purchase.id %>">
                            <td><%= direct_purchase.received_purchase_order.delivery_order_number %></td>
                            <td align="right"><%= direct_purchase.quantity_received %></td>
                            <td align="right"><%= number_to_currency(direct_purchase.receiving_value,
                                  :separator => ",",
                                  :delimiter => ".",
                                  :unit => "Rp",
                                  :precision => 2) %></td>
                            <td>
                                <% if direct_purchase.first_discount.present? %>
                                  <%= number_to_currency((direct_purchase.first_discount.to_f / 100) * direct_purchase.receiving_value,
                                    :separator => ",",
                                    :delimiter => ".",
                                    :unit => "Rp",
                                    :precision => 2) %> (<%= "#{direct_purchase.first_discount}%" %>)
                                <% end %>
                            </td>
                            <td>
                                <% if direct_purchase.second_discount.present? %>
                                  <%= number_to_currency(get_second_discount_in_money_for_ap(direct_purchase),
                                    :separator => ",",
                                    :delimiter => ".",
                                    :unit => "Rp",
                                    :precision => 2) %> (<%= "#{direct_purchase.second_discount}%" %> from <%= direct_purchase.is_additional_disc_from_net ? "net" : "gross" %>)
                                <% end %>
                            </td>
                            <td style="text-align: right">
                                <% if direct_purchase.is_taxable_entrepreneur %>
                                  <%
                                  vat_in_money = if direct_purchase.vat_type.eql?("include")
                                    get_include_vat_in_money_for_ap(direct_purchase)
                                    else
                                    get_vat_in_money_for_ap(direct_purchase)
                                    end
                                %>
                                  (<%= direct_purchase.vat_type %>) <%= number_to_currency(vat_in_money,
                                    :separator => ",",
                                    :delimiter => ".",
                                    :unit => "Rp",
                                    :precision => 2) %>
                                <% end %>
                            </td>
                            <td align="right"><%= number_to_currency(value_after_ppn_for_ap(direct_purchase),
                                  :separator => ",",
                                  :delimiter => ".",
                                  :unit => "Rp",
                                  :precision => 2) %></td>
                        </tr>
                        <% total_amount_received_for_dp += value_after_ppn_for_ap(direct_purchase) %>
                      <% end %>
                  </tbody>
                  <tfoot>
                      <tr>
                          <td colspan="6" align="right"><strong>Total Amount Received</strong></td>
                          <td align="right"><strong><%= number_to_currency(total_amount_received_for_dp,
                                    :separator => ",",
                                    :delimiter => ".",
                                    :unit => "Rp",
                                    :precision => 2) %></strong></td>
                      </tr>
                      <% if @account_payable && @account_payable.errors[:total].present? %>
                        <tr>
                            <td colspan="8" align="right"><%= error_help_text(@account_payable, :total) %></td>
                        </tr>
                      <% end %>
                  </tfoot>
              </table>              
          </div>
      </div>
      <!--
      SUDAH TIDAK DIPAKAI
            <div id="allocated_return_items_for_dp">
      <%# if params[:action].eql?("create_dp_payment") && @account_payable.allocated_return_items.present? %>
      <%#= render partial: "allocated_return_items", locals: {total_amount_received: total_amount_received_for_dp} %>
      <%# end %>
            </div>
      -->
      <div class="form-group">
          <label class="col-sm-2 control-label">Amount Due</label>
          <div class="col-sm-10">              
              <table class="table">
                  <tfoot>
                      <tr>
                          <td align="right" id="amount-to-pay-for-dp"><strong><%= number_to_currency(total_amount_received_for_dp,
                                    :separator => ",",
                                    :delimiter => ".",
                                    :unit => "Rp",
                                    :precision => 2) %></strong></td>
                      </tr>
                  </tfoot>
              </table>
          </div>
      </div>
      <div class="form-group">
          <label class="col-sm-2 control-label">
              Vendor
          </label>
          <div class="col-sm-10">
              <span class="form-control" id="vendor_id_for_dp" style="cursor: not-allowed;display: inline-block;width: auto"><%= @account_payable.vendor.name rescue "" %></span>
          </div>
      </div>
      <div class="form-group<%= control_group_error(@account_payable, :vendor_invoice_number) %>">
          <%= f.label :vendor_invoice_number, class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
                <%= f.text_field :vendor_invoice_number, class: "form-control" %>
                  <%= error_help_text(@account_payable, :vendor_invoice_number) %>
              </div>
          </div>
          <div class="form-group<%= control_group_error(@account_payable, :vendor_invoice_date) %>">
              <%= f.label :vendor_invoice_date, class: "col-sm-2 control-label" %>
                <div class="col-sm-10">
                    <%= f.text_field :vendor_invoice_date, size: 10, readonly: true, class: "form-control", id: "account_payable_vendor_invoice_date_dp" %>
                      <%= error_help_text(@account_payable, :vendor_invoice_date) %>
                  </div>
              </div>
              <div class="form-group<%= control_group_error(@account_payable, :note) %>">
                  <%= f.label :note, class: "col-sm-2 control-label" %>
                    <div class="col-sm-10">
                        <%= f.text_area :note, rows: 6, class: "form-control" %>
                          <%= error_help_text(@account_payable, :note) %>
                      </div>
                  </div>
                  <div class="form-group">
                      <div class="col-sm-offset-2 col-sm-10">
                          <%= f.submit "Save", class: "btn btn-primary", id: "ap_save_btn_for_dp" %>
                            <button class="btn btn-link cancel">Cancel</button>
                        </div>
                    </div>
                  <% end %>

                  <script>
                    $(function () {
                        $("#account_payable_vendor_invoice_date_dp").datepicker({
                            dateFormat: "dd/mm/yy"
                        });
                    });
                  </script>

app/views/account_payables/create_dp_payment.js.erb
<% if @account_payable.valid? %>
  <%= smart_listing_item :account_payables, :create, @account_payable, "account_payables/account_payable" %>
<% else %>
  $("#form_container_dp").html("<%= j(render(partial: "payment_form_for_dp")) %>");
<% end %>

<% if @vendor_name.present? %>
  $("#vendor_name_<%= @account_payable.id %>").html("<%= @vendor_name %>");
  $("#show_detail_ap_<%= @account_payable.id %>").click();
<% end %>

app/views/account_payables/generate_dp_payment_form.js.erb
$("#form_container_dp").html("<%= j(render(partial: "payment_form_for_dp")) %>");

app/views/account_payables/generate_form.js.erb
$("#form_container").html("<%= j(render(partial: "payment_form")) %>");

app/views/account_payables/get_received_purchases.js.erb
$("#ap_invoice_received_purchases_container").html("<%= j(render(partial: "received_purchases")) %>")

app/views/account_payables/index.html.erb
<div class="page-header">
    <h1>AP Invoices</h1>
</div>

<div id="search-form-container" class="form-inline text-right">
    <div class="form-group">
        <input type="text" class="form-control" id="filter-ap-invoice-invoice-number" placeholder="Invoice number">
    </div>
    <div class="form-group text-left">
        <%= select_tag "vendor_id", options_from_collection_for_select(Vendor.select(:id, :code, :name).where(is_active: true), :id, "code_and_name"), {include_blank: true, class: "form-control", id: "filter-ap-invoice-vendor-id"} %>
      </div>
      <div class="form-group">
          <input type="text" class="form-control" readonly="true" id="filter-ap-invoice-vendor-invoice-date" placeholder="Vendor Inv. Date">
      </div>
      <div class="form-group">
          <input type="text" class="form-control" readonly="true" id="filter-ap-invoice-due-date" placeholder="Due date">
      </div>
      <div class="form-group text-left">
          <%= select_tag "invoice_status", options_for_select(AccountPayable::INVOICE_STATUSES), {include_blank: true, class: "form-control", id: "filter-ap-invoice-status"} %>
        </div>
        <button id="search-ap-invoice-btn" type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-search"></span></button>
    </div>

    <div class="hidden">
        <%= smart_listing_controls_for(:account_payables, {class: "form-inline text-right"}) do %>
            <%= text_field_tag :filter_ap_invoice_invoice_number, '', class: "search form-control", autocomplete: :off %>
              <%= text_field_tag :filter_ap_invoice_vendor_id, '', class: "search form-control", autocomplete: :off %>
                <%= text_field_tag :filter_ap_invoice_vendor_invoice_date, '', class: "search form-control", autocomplete: :off %>
                  <%= text_field_tag :filter_ap_invoice_due_date, '', class: "search form-control", autocomplete: :off %>
                    <%= text_field_tag :filter_ap_invoice_status, '', class: "search form-control", autocomplete: :off %>
                    <% end %>
                </div>

                <%= smart_listing_render(:account_payables) %>
                <div id="print_ap_invoice_container"></div>

app/views/account_payables/new.js.erb
<% if @account_payable.beginning_of_account_payable_creating.eql?("Closed/Finish") %>
  <%= smart_listing_item :account_payables, :new, @account_payable, "account_payables/form" %>
<% else %>
  <%= smart_listing_item :account_payables, :new, @account_payable, "account_payables/form_partial" %>
<% end %>

app/views/account_payables/show.js.erb
<% if @account_payable.beginning_of_account_payable_creating.eql?("Partial") %>
  <%= smart_listing_item :account_payables, :edit, @account_payable, "account_payables/show_partial" %>
<% else %>
  <%= smart_listing_item :account_payables, :edit, @account_payable, "account_payables/show" %>
<% end %>