config/routes.rb
Rails.application.routes.draw do
  resources :print_barcode_temps, only: [:new, :create] do    
    collection do
      get "search_product"
      get "add_product"
    end
  end
  resources :accounts_receivable_payments, except: [:edit, :update, :destroy] do
    collection do
      get "generate_form"
      get "get_account_numbers"
    end
  end
  resources :accounts_receivable_invoices, only: [:index, :show] do
    collection do
      get "customer_debts"
      get 'overdue_invoice_list'
    end
    member do
      get "print"
    end
  end
  resources :account_payable_courier_payments, except: [:edit, :update, :destroy] do
    collection do
      get "generate_form"
      get "get_account_numbers"
    end
    member do
      get "print"
    end
  end
  resources :account_payable_couriers, except: [:edit, :update] do
    collection do
      get "get_packing_lists"
      get 'overdue_invoice_list'
    end
    member do
      get "print"
    end
  end  
  resources :general_variables, except: [:show, :destroy, :index]
  resources :packing_lists, except: [:edit, :update] do
    member do
      get 'print'
    end
    collection do
      get 'get_courier_ways'
      get 'get_courier_units'
      get 'get_courier_price_types'
      get 'get_courier_cities'
      get 'generate_packing_list_item_form'
      get :autocomplete_shipment_number
    end
  end
  resources :courier_prices do
    collection do
      get "get_courier_ways"
      get "get_courier_units"
    end
  end
  resources :account_payable_payments, except: [:edit, :update, :destroy] do
    collection do
      get "generate_form"
      get 'get_purchase_returns'
      get 'select_purchase_return'
      get "get_account_numbers"
    end
    member do
      get "print"
    end
  end
  resources :adjustments, except: [:edit, :update, :destroy] do
    collection do
      get :autocomplete_product_code
      get :get_product
    end
  end
  get 'import_beginning_stocks' => 'import_beginning_stocks#new'

  post 'import_beginning_stocks/create'

  get 'sell_thru' => 'sell_thrus#index'
  get 'quantity_sold_charts/index'
  resources :targets
  get 'growth_reports/index'
  get 'growth_reports/print'
  get 'growth_reports/export'

  namespace :api, defaults: { format: :json } do
    resources :stock_mutations do
      collection do
        get "store_to_store_inventory_receipts"
        get "search"
      end
      member do
        get "receive"
      end
    end
    resources :consignment_sales do
      collection do
        get "get_events"
        get "get_product"
      end
      member do
        get "approve"
        get "unapprove"
      end
    end
    resources :shipments, except: [:edit, :update] do
      collection do
        get "inventory_receipts"
        get "search_do"
      end
      member do
        get "receive"
      end
    end
    devise_for :users, only: :sessions
  end

  resources :customers do
    collection do
      get "get_cities"
    end
  end
  resources :consignment_sales do
    collection do
      get "get_product"
      get "get_product_colors"
      get "get_product_sizes"
      get "get_events"
    end
    member do
      get "approve"
      get "unapprove"
    end
  end
  get 'incompatible_browsers/index'

  resources :sales_returns, except: [:edit, :update, :destroy] do
    collection do
      get "search_receipt"
      get "get_replacement_product"
      get "get_replacement_product_colors"
      get "get_replacement_product_sizes"
    end
  end
  

  resources :counter_events do
    collection do
      get "generate_warehouse_form"
      get "add_products"
      get "add_general_products"
      get "get_warehouse"
    end
    member do
      get "generate_activation_form"
      patch "activate_deactivate"
    end
  end
  resources :companies
  resources :sales, except: [:edit, :update, :destroy] do
    collection do
      get "get_member"
      get "get_product"
      get "get_free_product"
      get "get_product_colors"
      get "get_free_product_colors"
      get "get_product_sizes"
      get "get_free_product_sizes"
      get "get_gift_event_product"
      get "get_gift_event_product_colors"
      get "get_gift_event_product_sizes"
      get 'export'
      get 'get_stock_detail'
      get 'search_product'
    end
    member do
      get "print"
      get "print_return_receipt"
    end
  end
  resources :members
  resources :banks, except: :show
  resources :cash_disbursements, only: [:index, :new, :create]
  resources :cashier_openings, except: [:edit, :update, :destroy] do
    member do
      get "close"
    end
  end
  resources :events do
    collection do
      get :autocomplete_events
      post :new_add_general_products
      post :new_add_products
      get "generate_warehouse_form"
      get "add_products"
      get "add_general_products"
    end
    member do
      get "generate_activation_form"
      patch "activate_deactivate"
    end
  end
  resources :listing_stocks, only: :index do
    collection do
      get :print
    end
  end
  resources :stock_movements, only: :index do
    collection do
      get :print
    end
  end
  resources :fiscal_years
  resources :goods_in_transits, only: [:shipment_goods, :mutation_goods, :returned_goods] do
    collection do
      get "shipment_goods"
      get "mutation_goods"
      get "returned_goods"
    end
    member do
      get "show_shipment_goods"
      get "show_mutation_goods"
      get "show_returned_goods"
    end
  end

  resources :stock_mutations do
    collection do
      get "get_products"
      get "get_saved_products"
      get "index_store_to_warehouse_mutation"
      get "show_store_to_warehouse_mutation"
      get "new_store_to_warehouse_mutation"
      get "store_to_store_inventory_receipts"
      get "store_to_warehouse_inventory_receipts"
      post "create_store_to_warehouse_mutation"
      get "search"
    end
    member do
      get "approve"
      get "show_store_to_store_receipt"
      get "show_store_to_warehouse_receipt"
      get "receive"
      get "receive_to_warehouse"
      get "print_rolling_doc"
      get "print_return_doc"
      delete "delete_store_to_warehouse"
      get "change_receive_date"
    end
  end
  resources :notifications, only: [:index, :show, :destroy, :notify_user] do
    collection do
      get "notify_user"
    end
  end
  resources :available_menus, only: [:new, :create]
  resources :shipments, except: [:edit, :update] do
    collection do
      get "generate_ob_detail"
      get "inventory_receipts"
      get "search_do"
      get :multiprint
      get :direct_sales
    end
    member do
      get "receive"
      get "change_receive_date"
      get "print"
      get "show_direct_sale"
    end
  end
  resources :couriers
  resources :order_bookings do
    collection do
      get "get_warehouse_products"
      get "generate_product_item_form"
      get "add_destination_warehouse"
      get "search_dest_warehouse"
    end
    member do
      get "picking_note"
    end
  end
  resources :account_payables, only: [:new, :create, :index, :destroy, :show] do
    collection do
      get 'generate_form'
      get 'generate_dp_payment_form'
      get 'get_purchase_returns_for_dp'
      get 'select_purchase_return_for_dp'
      post 'create_dp_payment'
      get 'get_received_purchases'
      get 'overdue_invoice_list'
    end
    member do
      get 'print'
    end
  end
  resources :emails
  resources :receiving, only: [:new, :create, :index, :show] do
    get :autocomplete_product_code, :on => :collection
    collection do
      get "get_product_details"
      get "search_do_numbers"
      get "goods_received_not_invoiced"
    end

    member do
      get 'get_purchase_order'
      post 'receive_products_from_purchase_order'
      get 'check_grni'
    end
  end

  resources :purchase_returns, except: [:destroy, :edit, :update] do
    collection do
      get 'get_purchase_order_details'
      get 'get_direct_purchase_details'
      post 'create_direct_purchase_return'
      get 'filter_purchase_records'
    end
    member do
      get 'print'
    end
  end
  resources :stocks, only: :index
  devise_for :users, only: :sessions
  resources :users do
    collection do
      get "generate_spg_user_form"
      get "get_area_manager_info"
    end
  end

  get 'welcome/index'

  resources :purchase_orders do
    get :autocomplete_product_code, :on => :collection
    collection do
      get 'get_product_details'
    end

    member do
      get 'close'
      get 'print'
      get 'export'
    end
  end
  resources :products do
    collection do
      get 'populate_detail_form'
      get 'import'
      post 'import'
    end
  end
  resources :size_groups, except: :show
  resources :sales_promotion_girls
  resources :warehouses do
    collection do
      get 'get_cities'
    end
  end
  resources :price_codes, except: :show
  resources :area_managers do
    member do
      get "get_warehouses"
    end
  end
  resources :vendors
  resources :regions, except: :show
  resources :goods_types, except: :show
  resources :models, except: :show
  resources :colors, except: :show
  resources :brands, except: :show
  resources :cost_prices do
    collection do
      get "generate_form"
      get "autocomplete_product"
      patch "create"
    end
  end

  root 'welcome#index'
  mount ActionCable.server => '/cable'

end

app/helpers/sales_helper.rb
module SalesHelper
  def get_event_value(store_event, row_index, free_product=nil)
    unless free_product.nil?
      return "BOGO: <span id='bogo_product_detail_container_#{row_index}'>#{free_product.name}/#{free_product.color_name}/#{free_product.product_size}</span><br /><button type='button' class='btn btn-primary btn_add_bogo_product' id='btn_add_bogo_product_#{row_index}'><span class='glyphicon glyphicon-edit'></span> Edit</button>".html_safe if store_event["event_type"].eql?("Buy 1 Get 1 Free")
    else
      return "BOGO: <span id='bogo_product_detail_container_#{row_index}'></span><br /><button type='button' class='btn btn-primary btn_add_bogo_product' id='btn_add_bogo_product_#{row_index}'><span class='glyphicon glyphicon-plus'></span> Add</button>".html_safe if store_event["event_type"].eql?("Buy 1 Get 1 Free")
    end
    return "#{store_event["first_plus_discount"]}% + #{store_event["second_plus_discount"]}%" if store_event["first_plus_discount"].present? && store_event["second_plus_discount"].present?
    return "#{store_event["first_plus_discount"]}%" if store_event["first_plus_discount"].present?
    return "#{number_to_currency(store_event["cash_discount"], :separator => ",", :delimiter => ".", :unit => "Rp", :precision => 2)}" if store_event["cash_discount"].present?
    return "Special price: #{number_to_currency(store_event["special_price"], :separator => ",", :delimiter => ".", :unit => "Rp", :precision => 2)}" if store_event["special_price"].present?
  end  
end

app/views/sales/_bogo_form.html.erb
<div id="bogo-product-form-<%= row_index %>" class="form-horizontal bogo-product-forms-<%= row_index %>" style="display: none;">
    <div class="form-group">
        <label class="col-sm-3 control-label">Barcode</label>
        <div class="col-sm-9">
            <div class="input-group">
                <input type="text" id="bogo_product_barcode_<%= row_index %>" class="form-control bogo_product_barcode" style="width: 100%">
                <span class="input-group-btn">
                    <button type="button" class="btn btn-primary search-barcode-btn-bogo" style="margin-bottom: 0px !important" id="search-barcode-btn-bogo-<%= row_index %>">
                        <span class="glyphicon glyphicon-plus"></span> Add
                    </button>
                </span>
            </div>
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-3 control-label">Product Code</label>
        <div class="col-sm-9">
            <input type="text" id="bogo_product_code_<%= row_index %>" name="bogo_product_code" class="form-control upcase bogo_product_code" style="width: 100%">
        </div>
    </div>

    <div id="sale_product_bogo_color_field_container_<%= row_index %>">

    </div>

    <div id="sale_product_bogo_size_field_container_<%= row_index %>">

    </div>

    <div class="form-group">
        <div class="col-xs-5 col-xs-offset-3">
            <button type="button" class="btn btn-primary hidden" id="modal_form_btn_add_bogo_product_<%= row_index %>">
                <span class="glyphicon glyphicon-plus"></span> Add
            </button>
        </div>
    </div>
</div>

app/views/sales/_listing.html.erb
<table class="table table-striped" style="table-layout: fixed;word-wrap: break-word;">
    <thead id="listing-sales-thead">
        <tr>
            <th class="col-md-3"><%= smart_listing.sortable "Transaction Number", "transaction_number" %></th>
            <th class="col-md-2"><%= smart_listing.sortable "Transaction Time", "transaction_time" %></th>
            <th class="col-md-2"><%= smart_listing.sortable "Payment Method", "payment_method" %></th>
            <th class="col-md-2"><%= smart_listing.sortable "Total", "total" %></th>
            <th class="col-md-2"><%= smart_listing.sortable "Gross Profit", "gross_profit" %></th>
            <th class="col-md-1"></th>
        </tr>
    </thead>
    <tbody>
        <% smart_listing.collection.each do |sale| %>
          <tr class="editable" data-id="<%= sale.id %>">
              <%= smart_listing.render object: sale, partial: "sales/sale", locals: {object: sale} %>
          </tr>
        <% end %>
        <%#= smart_listing.item_new colspan: 4, link: new_cash_disbursement_path %>
    </tbody>
</table>
<%= smart_listing.paginate %>
<script>
  var processId = setInterval(function () {
      if ($("#listing-sales-thead").is(":visible")) {
          clearInterval(processId);
      } else {
          $("#listing-sales-thead").show();
      }
  }, 0);
</script>

app/views/sales/_purchased_product_fields.html.erb
<%#= fields_for "sale[sale_products_attributes][#{sale_product.product_barcode_id}]", sale_product do |sale_product_fields| %>
<%= fields_for "sale[sale_products_attributes][#{form_fields_index}]", sale_product do |sale_product_fields| %>
  <%= sale_product_fields.hidden_field :product_barcode_id %>
  <%= sale_product_fields.hidden_field :event_id %>
  <%= sale_product_fields.hidden_field :free_product_id %>
  <%= sale_product_fields.hidden_field :product_spg_id %>
  <%= sale_product_fields.hidden_field :attr_product_spg_name %>
  <!--
    <div class="form-group<%#= control_group_error(sale_product_fields.object, :quantity) %>">
  <%#= sale_product_fields.text_field :quantity, class: "form-control sale-product-quantity-fields", style: "width: 75px; text-align: center", id: "sale-product-quantity-#{sale_product.product_barcode_id}" %>
  <%#= error_help_text(sale_product_fields.object, :quantity) %>
      </div>-->
<% end %>

app/views/sales/_sale_gift_event_product_sizes_field.html.erb
<div class="form-group">
    <label class="col-sm-3 control-label">Size</label>
    <div class="col-sm-9">
        <%= select_tag "sale_gift_event_product_size", options_from_collection_for_select(@product_sizes, :id, :size), {include_blank: true, class: "form-control", style: "width: 100%;"} %>
      </div>
  </div>

app/views/sales/create.js.erb
<% if @generate_add_gift_form %>
  bootboxDialogFormGiftEvent = bootbox
          .dialog({
              title: 'Add Gift',
              message: $('#addSaleGiftForm'),
              show: false, /* We will show it manually later */
              onEscape: true
          }).on('shown.bs.modal', function () {
      $('#addSaleGiftForm')
              .show();
      $("#discount_product").attr("data-placeholder", "Please select").chosen("destroy").chosen();
      $('#discount_product').val('').trigger('chosen:updated');
      $("#sale_event_gift_discount_amount").html("<%= @discount_amount %>");
      $("#sale_event_gift_discount_amount").toCurrency({
        precision: 2, // decimal precision
        delimiter: ".", // thousands delimiter
        separator: ",", // decimal separator
        unit: "Rp", // unit
        format: "%u%n", // format. %u is the placeholder for the unit, %n for the number
        negativeFormat: false   // format for negative numbers. If false, it defaults to the same format as positive numbers
      });
      $("#sale_event_gift_discount_amount_field_layout").addClass("hidden");
      $(".gift-event-product-search-fields").addClass("hidden");
      $("#modal_form_btn_add_event_gift_product").addClass("hidden");
      $("#sale_event_gift_product_color_field_container").html("");
      $("#sale_event_gift_product_size_field_container").html("");
  }).on('hide.bs.modal', function (e) {
      $('#addSaleGiftForm').hide().appendTo('body');
  }).modal('show');
<% else %>
  <% if @valid %>
    window.location = '<%= new_sale_path %>?print_receipt=<%= @sale.id %>&product_spg_names=<%= @product_spg_names %>';
  <% else %>
    $("#stepContainer").html("<%= j(render(partial: "wizard_form")) %>");
    <% if @sale.errors.details.keys.include?(:member_id) %>
      $("#list-step-1").click();
    <% elsif @sale.errors.details.keys.include?(:payment_method) || @sale.errors.details.keys.include?(:bank_id) || @sale.errors.details.keys.include?(:trace_number) || @sale.errors.details.keys.include?(:card_number) || @sale.errors.details.keys.include?(:cash) || @sale.errors.details.keys.include?(:gift_event_id) || @sale.errors.details.keys.include?(:gift_event_product_id) %>
      $("#list-step-3").click();
    <% else %>
      $("#list-step-2").click();
    <% end %>
  <% end %>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form', sale: @sale %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/export.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
    <Worksheet ss:Name="Sheet1">
        <Table>
            <Row>
                <Cell><Data ss:Type="String">Showroom</Data></Cell>
                <Cell><Data ss:Type="String">Date</Data></Cell>
                <Cell><Data ss:Type="String">Transaction Number</Data></Cell>
                <Cell><Data ss:Type="String">Article</Data></Cell>
                <Cell><Data ss:Type="String">Color</Data></Cell>
                <Cell><Data ss:Type="String">Size</Data></Cell>
                <Cell><Data ss:Type="String">Quantity</Data></Cell>
                <Cell><Data ss:Type="String">Gross Amt</Data></Cell>
                <Cell><Data ss:Type="String">Event</Data></Cell>
                <Cell><Data ss:Type="String">Discount</Data></Cell>
                <Cell><Data ss:Type="String">Member Discount</Data></Cell>
                <Cell><Data ss:Type="String">Net Amt</Data></Cell>
                <Cell><Data ss:Type="String">Gross Profit</Data></Cell>
                <Cell><Data ss:Type="String">Payment Method</Data></Cell>
            </Row>

            <% @sale_products.each do |sale_product| %>
              <% total_quantity = @sale_products.select{|sp| sp.transaction_number == sale_product.transaction_number}.length %>
              <Row>
                  <Cell><Data ss:Type="String"><%= sale_product.warehouse_name %></Data></Cell>
                  <Cell><Data ss:Type="String"><%= sale_product.transaction_time.to_date.strftime("%d/%m/%Y") %></Data></Cell>
                  <Cell><Data ss:Type="String"><%= sale_product.transaction_number %></Data></Cell>
                  <Cell><Data ss:Type="String"><%= "#{sale_product.product_code} - #{sale_product.brand_name}" %></Data></Cell>
                  <Cell><Data ss:Type="String"><%= "#{sale_product.color_code} - #{sale_product.color_name}" %></Data></Cell>
                  <Cell><Data ss:Type="String"><%= sale_product.product_size %></Data></Cell>
                  <Cell><Data ss:Type="Number">1</Data></Cell>
                  <Cell><Data ss:Type="String"><%= number_to_currency(sale_product.price, :separator => ",", :delimiter => ".", :unit => "Rp", :precision => 2) %></Data></Cell>
                  <% if sale_product.free_product_id.present? %>
                    <Cell><Data ss:Type="String">BOGO</Data></Cell>
                  <% elsif sale_product.sale_first_plus_discount.present? && sale_product.sale_second_plus_discount.present? %>
                    <Cell><Data ss:Type="String"><%= "#{sale_product.sale_first_plus_discount}% + #{sale_product.sale_second_plus_discount}%" %></Data></Cell>
                  <% elsif sale_product.sale_first_plus_discount.present? %>                    
                    <Cell><Data ss:Type="String"><%= "#{sale_product.sale_first_plus_discount}%" %></Data></Cell>
                  <% elsif sale_product.sale_cash_discount.present? %>
                    <Cell><Data ss:Type="String"><%= number_to_currency(sale_product.sale_cash_discount, :separator => ",", :delimiter => ".", :unit => "Rp", :precision => 2) %></Data></Cell>                    
                  <% elsif sale_product.special_price.present? %>                    
                    <Cell><Data ss:Type="String"><%= "Special price: #{number_to_currency(sale_product.special_price, :separator => ",", :delimiter => ".", :unit => "Rp", :precision => 2)}" %></Data></Cell>
                  <% else %>
                    <Cell><Data ss:Type="String"></Data></Cell>
                  <% end %>                                  
                  <% if sale_product.sale_event_type.eql?("Gift") && sale_product.gift_event_product_id.blank? %>
                    <Cell><Data ss:Type="String"><%= number_to_currency(sale_product.discount_amount.to_f / total_quantity, :separator => ",", :delimiter => ".", :unit => "Rp", :precision => 2) %></Data></Cell>
                  <% end %>
                  <%
                  member_discount = if sale_product.member_id.present?
                    if sale_product.sale_event_type.eql?("Gift") && sale_product.gift_event_product_id.blank?
                      subtotal_before_discount_member = (sale_product.total * 100).to_f / (100 - sale_product.member_discount)
                      subtotal_after_gift_discount = subtotal_before_discount_member - (sale_product.discount_amount.to_f / total_quantity)
                      subtotal_after_discount_member = subtotal_after_gift_discount - subtotal_after_gift_discount * (sale_product.member_discount.to_f / 100)
                      subtotal_after_gift_discount - subtotal_after_discount_member
                      else
                      subtotal_before_discount_member = (sale_product.total * 100).to_f / (100 - sale_product.member_discount)
                      subtotal_before_discount_member - sale_product.total
                    end
                    else
                  0
                    end
                %>
                  <Cell><Data ss:Type="String"><%= number_to_currency(member_discount, :separator => ",", :delimiter => ".", :unit => "Rp", :precision => 2) %></Data></Cell>
                  <%
                  total = if sale_product.sale_event_type.eql?("Gift") && sale_product.gift_event_product_id.blank?
                    if sale_product.member_id.present?
                      subtotal_before_discount_member = (sale_product.total * 100).to_f / (100 - sale_product.member_discount)
                      subtotal_after_gift_discount = subtotal_before_discount_member - (sale_product.discount_amount.to_f / total_quantity)
                      subtotal_after_gift_discount - subtotal_after_gift_discount * (sale_product.member_discount.to_f / 100)
                      else
                      sale_product.total - (sale_product.discount_amount.to_f / total_quantity)
                    end
                    else
                    sale_product.total
                    end
                %>
                  <Cell><Data ss:Type="String"><%= number_to_currency(total, :separator => ",", :delimiter => ".", :unit => "Rp", :precision => 2) %></Data></Cell>
                  <Cell><Data ss:Type="String"><%= number_to_currency(sale_product.gross_profit, :separator => ",", :delimiter => ".", :unit => "Rp", :precision => 2) %></Data></Cell>
                  <Cell><Data ss:Type="String"><%= sale_product.payment_method %></Data></Cell>
              </Row>
            <% end %>
        </Table>
    </Worksheet>
</Workbook>

app/views/sales/get_gift_event_product_sizes.js.erb
<% if @product_sizes.blank? %>    
  var box = bootbox.alert({message: "Size is not available",size: 'small'});
<% else %>
  $("#sale_event_gift_product_size_field_container").html("<%= j(render(partial: "sale_gift_event_product_sizes_field")) %>");
  $("#sale_gift_event_product_size").attr("data-placeholder", "Select").chosen("destroy").chosen();
  $("#modal_form_btn_add_event_gift_product").removeClass("hidden");
<% end %>

app/views/sales/index.html.erb
<div class="page-header">
    <h1>Sales</h1>
</div>

<div id="search-form-container" class="form-inline text-right">
    <% if current_user.has_non_spg_role? %>
      <div class="form-group text-left">
          <%= select_tag "warehouse_id", options_from_collection_for_select(Warehouse.showroom.actived.select(:id, :code, :name), :id, "code_and_name"), {include_blank: true, class: "form-control", id: "filter-sale-warehouse-id"} %>
        </div>
      <% end %>
      <div class="form-group">
          <input type="text" id="filter-string" class="form-control" placeholder="Transaction number">
      </div>
      <div class="form-group">
          <input type="text" class="form-control" readonly="true" id="filter-sale-transaction-time" placeholder="Transaction date" style="width: 200px !important">
      </div>
      <div class="form-group">
          <%= select_tag "payment_method", options_for_select(Sale::PAYMENT_METHODS+[["Memo", "Memo"]]), {prompt: "Payment method", class: "form-control", id: "filter-payment-method"} %>
        </div>
        <button id="search-sale-btn" type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-search"></span></button>
        <button id="export-sale-btn" type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-export"></span></button>
    </div>

    <div class="hidden">
        <%= smart_listing_controls_for(:sales, {class: "form-inline text-right"}) do %>
            <%= text_field_tag :filter_warehouse, '', class: "search form-control", autocomplete: :off %>
              <%= text_field_tag :filter_date, '', class: "search form-control", autocomplete: :off %>
                <%= text_field_tag :filter_string, '', class: "search form-control", autocomplete: :off %>
                  <%= text_field_tag :filter_payment_method, '', class: "search form-control", autocomplete: :off %>
                  <% end %>

                  <%= form_tag(export_sales_path(format: :xls), method: :get, id: :export_pos) do %>
                    <%= text_field_tag :filter_warehouse_export, '', class: "search form-control", autocomplete: :off %>
                      <%= text_field_tag :filter_date_export, '', class: "search form-control", autocomplete: :off %>
                        <%= text_field_tag :filter_string_export, '', class: "search form-control", autocomplete: :off %>
                          <%= text_field_tag :filter_payment_method_export, '', class: "search form-control", autocomplete: :off %>
                          <% end %>
                      </div>
                      <%= smart_listing_render(:sales) %>

                      <div id="receipt-container"></div>

app/views/sales/index.js.erb
<%= smart_listing_update(:sales) %>